// layout.js melaf y7ade elmochtarek eli bach tath-har fel saf7at
// layout felapp directory kolhom y7slo 3al lyout 

import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// #children ymathal kol saf7at -- y5arj mo7taw elsf7a
export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
         <nav 
         style={{
          width:"100%",
           background:"teal", 
           fontSize:"30px", 
           height:"50px",
            display:"flex",
             justifyContent:"center",
             alignItems:"center",
             }}>
        <Link style={{margin:"10px"}} href="/">Home</Link>
        <Link style={{margin:"10px"}} href="/posts">Posts</Link>
        <Link style={{margin:"10px"}} href="/articles">Articles</Link>
      </nav>
        {children}
        </body>
    </html>
  )
}
